# Build
FROM node:12.22.0-alpine AS build

WORKDIR /tmp

COPY package.json yarn.lock ./
COPY . .

RUN yarn --frozen-lockfile

RUN yarn build

# Runner
FROM node:12.22.0-alpine AS runner

WORKDIR /usr/src/app

COPY --from=build /tmp/node_modules ./node_modules
COPY --from=build /tmp/.next ./.next
COPY . .

EXPOSE 3000

CMD ["yarn", "start"]